name: Continuous Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cahce dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-18.x-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-18.x
            ${{ runner.OS }}-
      - name: Install dependencies
        run: |
          npm install
      - name: Lint and build
        run: |
          npm run lint
          npm run rollup
          npm run babel
      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: Set the release body
        id: release
        shell: bash
        run: |
          r=$(cat release_notes/v${{ env.RELEASE_VERSION }}.md)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"
      - name: Upload the release file
        uses: svenstaro/upload-release-action@v2.6.0
        with:
          file: dist/*
          file_glob: true
          overwrite: true
          promote: true
          body: |
            ${{ steps.release.outputs.RELEASE_BODY }}
